apiVersion: apps/v1
kind: Daemonset
metadata:
  name: daemon-set-name
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value1
spec:
  selector:
    matchLabels:
      label-key1: label-value1
    matchExpressions:
      - key: label-key1
        operator: In
        values:
          - label-value1
    template:
      metadata:
        name: nama-pod
        label:
          label-key: label-value
      spec:
       - container: name-container
         image: nama-image
         ports:  
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelay: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
 
