apiVersion: batch/v1
kind: CronJob
metadata:
  nama: nama-cron-job
  labels:
    label-key: label-value
  annotations:
    annotation-key1: annotation-value
spec:
  schedule: "* * * * *" # source set schedule cronjob.guru
  jobTemplate:
    spec:
      selector:
        matchLabels:
          label-key1: label-value1
      template: 
         metadata:
           name: pod-name
           labels:
             app: pod-la
         spec:
            restartPolicy: Never
            containers:
              - name: container-name
                image: image-name
                ports:
                  - containerport: 80
        
