apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-example
spec:
 minReplicas: 3
 maxReplicas: 5
 scaleTargetRef:
   apiVersion: apps/v1
   kind: deployment  #bisa pod bisa replicaSet bisa Statefulset target HPA nya
   name: nama-deployment
 metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 70
   - type: Resource
     resource:
       name: memory
       target:
         type: Utilization
         averageUtilization: 70
