apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: replica-set-name
  labels:
    label-key1: value-key1
  annotations:
    annotation-key1: annotation-value
spec:
  replicas: 3
  selector:
    matchLabels:
      label-key1: label-value1
    matchExpressions:
      - key: label-key
        operator: In
        values:
           - label-value1:
           - label-value2:
   template:
    metadata:
      name: pod-name
      labels:
        label-key1: label-value1
    spec:
      containers:
      - name: name-container
        image: image-name
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeoconds: 1
