apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap2-belajar
data:
  APPLICATION: aplikasi saya

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-belajar
stringData:
  Version: 2.0.0

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-belajar-value
spec:
  replicas: 3
  selector:
    matchLabels:
      name: rs-belajar-value
  template:
    metadata:
      name: rs-belajar-value
      labels:
        name: rs-belajar-value
    spec:
      containers:
        - name: nodejs-writer4
          image: khannedy/nodejs-env
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: configmap2-belajar
            - secretRef:
                name: secret-belajar
  
---

apiVersion: v1
kind: Service
metadata:
  name: secret-test-svc
spec:
  type: NodePort
  selector:
    name: rs-belajar-value
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
      