apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replicaset-sharevolume
spec:
  replicas: 3
  selector:
    matchLabels:
      name: test-replicaset-sharevolume
  template:
    metadata:
      labels:
        name: test-replicaset-sharevolume
    spec:
      volumes:
        - name: replica-share-volume
          emptyDir: {}
      containers:
          - name: nodejs-writer2
            image:  khannedy/nodejs-writer
            volumeMounts:
              - name:  replica-share-volume
                mountPath: /app/html
          - name:  nginx
            image: nginx
            ports:
            - containerPort: 80
            volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: replica-share-volume


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name:  test-replicaset-sharevolume
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001