apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-configmap
data:
  APPLICATION: My Cool App
  VERSION: 1.0.0

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-writer4
  labels:
    app: belajar
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nodejs-writer4
  template:
    metadata:
      labels:
        name: nodejs-writer4
        app: belajar
    spec:
      containers:
        - name: nodejs-writer4
          image: khannedy/nodejs-env
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: testing-configmap


---

apiVersion: v1
kind: Service
metadata:
  name:  testing-configmap-svc
spec:
  type: NodePort
  selector:
    name:  nodejs-writer4
    app: belajar
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001


  