apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-provider-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-rs-provider-lb
  template:
    metadata:
      name: nginx-rs-provider-lb
      labels:
        name: nginx-rs-provider-lb
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: servicelb
spec:
  type: LoadBalancer
  selector:
    name:  nginx-rs-provider-lb
  ports:
    - port: 80
      targetPort: 80

  