apiVersion: v1
kind: ConfigMap
metadata: 
  name: configmap2-belajar-dg
data:
  APPLICATION: 1.2.0
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-belajar-dg
spec:
  replicas: 3
  selector:
    matchLabels:
      name: rs-belajar-dg
  template:
    metadata:
      name: rs-belajar-dg
      labels:
        name: rs-belajar-dg
    spec:
      containers:
        - name: nodejs-env2
          image: khannedy/nodejs-env
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: configmap2-belajar-dg
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata: 
  name: svc-dg
spec:
  type: NodePort
  selector:
    name: rs-belajar-dg
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
