apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
  namespace: monitoring
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: uptime.dashboard.alan.id
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-kuma
  namespace: monitoring
spec:
  parentRefs:
    - name: test-gateway
      namespace: monitoring
  hostnames:
    - "uptime.dashboard.alan.id"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kuma-svc-local
          port: 3001
