apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kuma
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
    storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: uptimekuma-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptimekuma-d
  template:
    metadata:
      labels:
        app: uptimekuma-d
    spec:
     containers: 
       - name: uptime-kuma-containers
         image: louislam/uptime-kuma:1
         ports:
           - containerPort: 3001
         volumeMounts:
           - name: kumakuma-data
             mountPath: /app/data
     volumes:
       - name: kumakuma-data
         persistentVolumeClaim:
           claimName: pvc-kuma

---

apiVersion: v1
kind: Service
metadata:
 name: kuma-svc-local
spec:
 type: NodePort
 selector:
   app: uptimekuma-d
 ports:
   - port: 3001
     targetPort: 3001
     nodePort: 32112

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-ingress
  labels:
    name: uptime-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: uptime.dashboard.alan.id
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuma-svc-local # nama service di metadata 
                port:
                  number: 3001

    


