apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-es
  namespace: monitoring
  labels:
    component: elasticsearch
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
