apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rst
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rst
  template:
    metadata:
      name: nginx-rst
      labels:
        app: nginx-rst
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
