apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector
spec:
  nodeSelector: 
    gpu: "true" # label yang ada dinode supaya saat di create dia langsung ke node yang punya label serupa
  containers:
    - name: nginxcontainer
      image: nginx
      ports:
        - containerPort: 80

