apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx1
  template:
    metadata:
      name: nginx
      labels:
        name: nginx1
    spec:
      containers:
        - name: nginx1
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001