apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kuma
  namespace: monitoring
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: uptimekuma-d
  ports: 
    - port: 3001
      targetPort: 3001
      nodePort: 32122
