name: CI Minikube

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # untuk bisa bandingkan 2 commit

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Clone repo berisi manifest
        run: git clone https://github.com/Satriaaa16/Kubernetes-tutorial.git

      - name: Build image
        run: |
          cd Kubernetes-tutorial
          minikube image build -t local/devex:v1 .

      - name: Membuat namespace belajar
        run: kubectl create ns belajar || true

      - name: Cari dan deploy hanya file YAML yang berubah
        run: |
          echo "File YAML yang berubah:"
          git fetch origin
          git diff --name-only origin/master HEAD | grep '^Kubernetes-tutorial/belajar/example/.*\.ya\?ml$' || true > changed_files.txt

          cat changed_files.txt

          while read file; do
            [ -f "$file" ] && kubectl apply -f "$file" -n belajar || echo "File $file tidak ditemukan, dilewati..."
          done < changed_files.txt

      - name: Cek manifest berhasil atau engga
        run: | 
          echo "jadi gini bor"
          kubectl get all -n belajar
