name: CI Minikube Deploy All

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and deploy to Minikube
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Test cluster up
        run: kubectl get nodes -o wide

      - name: Clone repo berisi manifest
        run: git clone https://github.com/Satriaaa16/Kubernetes-tutorial.git

      - name: Build image (opsional, hanya kalau perlu)
        run: |
          cd Kubernetes-tutorial
          minikube image build -t local/devex:v1 .

      - name: Deploy semua manifest
        run: |
          kubectl apply -R -f Kubernetes-tutorial/

      - name: Tunggu semua pod ready
        run: |
          kubectl wait --for=condition=ready pod --all --all-namespaces --timeout=120s
          kubectl get all --all-namespaces
