name: CI Minikube Workload Only

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and deploy workloads + ConfigMap to Minikube
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Test cluster up
        run: kubectl get nodes -o wide

      - name: Clone repo berisi manifest
        run: git clone https://github.com/Satriaaa16/Kubernetes-tutorial.git

      - name: Install yq (YAML processor)
        run: sudo snap install yq

      - name: Buat namespace monitoring & devops
        run: |
          kubectl create ns monitoring || true
          kubectl create ns devops || true

      - name: Deploy workload + ConfigMap (skip template dir)
        run: |
          for file in $(find Kubernetes-tutorial/ -name "*.yaml" -o -name "*.yml"); do
            if [[ $file == *"belajar/template/"* ]]; then
              echo "⏭️ Skipping template file: $file"
              continue
            fi

            echo "🔎 Checking $file"
            count=$(yq e 'select(.kind == "Deployment" or 
                                .kind == "StatefulSet" or 
                                .kind == "DaemonSet" or 
                                .kind == "Job" or 
                                .kind == "CronJob" or 
                                .kind == "ReplicaSet" or 
                                .kind == "ConfigMap") | length' "$file" | wc -l)

            if [ "$count" -gt 0 ]; then
              echo "✅ Applying workloads from $file"
              yq e 'select(.kind == "Deployment" or 
                           .kind == "
