name: CI Minikube Workload Only

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and deploy workloads + ConfigMap to Minikube
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Test cluster up
        run: kubectl get nodes -o wide

      - name: Clone repo berisi manifest
        run: git clone https://github.com/Satriaaa16/Kubernetes-tutorial.git

      - name: Install yq (YAML processor)
        run: sudo snap install yq

      - name: Buat namespace monitoring & devops
        run: |
          kubectl create ns monitoring || true
          kubectl create ns devops || true

      - name: Deploy hanya workload + ConfigMap
        run: |
          for file in $(find Kubernetes-tutorial/ -name "*.yaml" -o -name "*.yml"); do
            echo "🔎 Checking $file"
            # cek per dokumen di file
            count=$(yq e 'select(.kind == "Deployment" or 
                                .kind == "StatefulSet" or 
                                .kind == "DaemonSet" or 
                                .kind == "Job" or 
                                .kind == "CronJob" or 
                                .kind == "ReplicaSet" or 
                                .kind == "ConfigMap") | length' "$file" | wc -l)
            if [ "$count" -gt 0 ]; then
              echo "✅ Applying workloads from $file"
              yq e 'select(.kind == "Deployment" or 
                           .kind == "StatefulSet" or 
                           .kind == "DaemonSet" or 
                           .kind == "Job" or 
                           .kind == "CronJob" or 
                           .kind == "ReplicaSet" or 
                           .kind == "ConfigMap")' "$file" | kubectl apply -f -
            else
              echo "⏭️ Skipping $file (bukan workload/ConfigMap)"
            fi
          done

      - name: Tunggu workload siap
        run: |
          kubectl wait --for=condition=available deployment --all --all-namespaces --timeout=120s || true
          kubectl wait --for=condition=ready pod --all --all-namespaces --timeout=120s || true
          kubectl get all --all-namespaces
