name: CI Minikube Workload + ConfigMap

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and deploy workloads + ConfigMap to Minikube
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Test cluster up
        run: kubectl get nodes -o wide

      - name: Clone repo berisi manifest
        run: git clone https://github.com/Satriaaa16/Kubernetes-tutorial.git

      - name: Build image (opsional, hanya kalau perlu)
        run: |
          cd Kubernetes-tutorial
          minikube image build -t local/devex:v1 .

      - name: Buat namespace monitoring & devops
        run: |
          kubectl create ns monitoring || true
          kubectl create ns devops || true

      - name: Deploy workload (Deployment, StatefulSet, dsb) + ConfigMap
        run: |
          for file in $(find Kubernetes-tutorial/ -name "*.yaml" -o -name "*.yml"); do
            if grep -qE "kind: (Deployment|StatefulSet|DaemonSet|Job|CronJob|ReplicaSet|ConfigMap)" "$file"; then
              echo "Deploying $file"
              kubectl apply -f "$file"
            else
              echo "Skipping $file (tidak termasuk workload/ConfigMap)"
            fi
          done

      - name: Tunggu workload siap
        run: |
          kubectl wait --for=condition=available deployment --all --all-namespaces --timeout=120s || true
          kubectl wait --for=condition=ready pod --all --all-namespaces --timeout=120s || true
          kubectl get all --all-namespaces
