name: CI Minikube

on:
  pull_request:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and deploy to Minikube
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Clone repo berisi manifest
        run: git clone https://github.com/Satriaaa16/Kubernetes-tutorial.git

      - name: Build image (non-functional on GitHub-hosted runner)
        run: |
          cd Kubernetes-tutorial
          minikube image build -t local/devex:v1 .

      - name: Membuat namespace monitoring
        run: kubectl create ns belajar || true

      - name: Deploy file YAML
        run: |
          kubectl apply -f /belajar/example -n monitoring

      - name: Cek manifest berhasil atau engga
        run: |
          kubectl wait --for=condition=ready pod --all -n belajar --timeout=60s
